### PR TITLE
Include patches up to 29.3rc2

### PR DESCRIPTION
**Pull request by ajtowns**
A few fairly straightforward merge conflicts needed resolving.

Includes a behaviour change for `mempool-script-verify-flag-failed` vs `mandatory-script-verify-flag-failed` errors, so that failures due to Inquisition soft forks are reported as `mempool-` for mempool addition, and `mandatory-` for block verification. (Without this change, once any soft fork is activated, all block verification failures will be reported as `mempool-` instead of `mandatory-`).

### CODE REVIEW

**Comment by darosior** [comment]
One of the CI issues seems trivial to fix (just the linter):
```
[178/665][18.9s] clang-tidy-19 -p=/home/runner/work/_temp/build -quiet -load=/tidy-build/libbitcoin-tidy.so /home/runner/work/_temp/src/init.cpp
/home/runner/work/_temp/src/init.cpp:1547:20: error: use emplace_back instead of push_back [modernize-use-emplace,-warnings-as-errors]
 1547 |         uacomments.push_back("inquisition");
      |                    ^~~~~~~~~~
      |                    emplace_back(
1863 warnings generated.

[179/665][10.7s] clang-tidy-19 -p=/home/runner/work/_temp/build -quiet -load=/tidy-build/libbitcoin-tidy.so /home/runner/work/_temp/src/node/mempool_persist.cpp
+ echo '^^^ ⚠️ Failure generated from clang-tidy'
+ false
1025 warnings generated.

[180/665][7.7s] clang-tidy-19 -p=/home/runner/work/_temp/build -quiet -load=/tidy-build/libbitcoin-tidy.so /home/runner/work/_temp/src/bitcoin-util.cpp
/home/runner/work/_temp/src/bitcoin-util.cpp:260:23: error: use emplace_back instead of push_back [modernize-use-emplace,-warnings-as-errors]
  260 |                 stack.push_back({});
      |                       ^~~~~~~~~~~~
      |                       emplace_back(
722 warnings generated.

--

[487/665][8.1s] clang-tidy-19 -p=/home/runner/work/_temp/build -quiet -load=/tidy-build/libbitcoin-tidy.so /home/runner/work/_temp/src/test/crypto_tests.cpp
953 warnings generated.

[488/665][14.7s] clang-tidy-19 -p=/home/runner/work/_temp/build -quiet -load=/tidy-build/libbitcoin-tidy.so /home/runner/work/_temp/src/test/script_tests.cpp
/home/runner/work/_temp/src/test/script_tests.cpp:942:29: error: use starts_with instead of find() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
  942 |                 if (element.find(scriptFlag) == 0) {
      |                             ^~~~~          ~~~~~~
      |                             starts_with(   )
/home/runner/work/_temp/src/test/script_tests.cpp:1804:13: error: use emplace_back instead of push_back [modernize-use-emplace,-warnings-as-errors]
 1804 |     witData.push_back({});
      |             ^~~~~~~~~~~~
      |             emplace_back(
/home/runner/work/_temp/src/test/script_tests.cpp:1805:13: error: use emplace_back instead of push_back [modernize-use-emplace,-warnings-as-errors]
 1805 |     witData.push_back({});
      |             ^~~~~~~~~~~~
      |             emplace_back(
/home/runner/work/_temp/src/test/script_tests.cpp:1819:13: error: use emplace_back instead of push_back [modernize-use-emplace,-warnings-as-errors]
 1819 |     witData.push_back({});
      |             ^~~~~~~~~~~~
      |             emplace_back(
1456 warnings generated.

^^^ ⚠️ Failure generated from clang-tidy
```

The other one seems more annoying, as it says the machine ran out of disk space?

**Comment by willcl-ark** [comment]
> The other one seems more annoying, as it says the machine ran out of disk space?

You might need to backport https://github.com/bitcoin/bitcoin/pull/33514 to clear out space on the GH runner :(

**Comment by ajtowns** [comment]
The "test each commit" job has no hope of succeeding since the inquisition changes introducing new soft forks and the bitcoin#33788 backport have silent merge conflicts. Seems better to have the fixes in proper commits.
